import Header from '@/components/header/header';
import RecoilRootProvider from '@/recoil/recoilRootProvider';
import type { Metadata } from 'next';
import { Archivo, Libre_Franklin } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
const libre_franklin = Libre_Franklin({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-libre_franklin'
});
const archivo = Archivo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-archivo'
});
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={libre_franklin.variable + ' ' + archivo.variable}>
        <RecoilRootProvider>
          <Header />
          {children}
          <ToastContainer />
        </RecoilRootProvider>
      </body>
    </html>
  );
}
