/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VW0YknhRdt1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { PaginationPrevious, PaginationItem, PaginationLink, PaginationEllipsis, PaginationNext, PaginationContent, Pagination } from "@/components/ui/pagination"

export function StudyList() {
  return (
    <div className="container mx-auto py-8 px-4 md:px-6 lg:px-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-3xl font-bold">Active Study Groups</h1>
        <Button size="sm">
          <PlusIcon className="w-4 h-4 mr-2" />
          Add Study Group
        </Button>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Link
          className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          href="#"
        >
          <div className="p-6">
            <div className="flex items-center justify-between mb-2">
              <h2 className="text-xl font-bold">Algorithms 101</h2>
              <div className="flex items-center">
                <UsersIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">15/20</span>
              </div>
            </div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center">
                <div className="flex items-center">
                  <CoinsIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                  <span className="text-gray-600 dark:text-gray-400">Penalty: 10,000 KRW</span>
                </div>
              </div>
              <div className="flex items-center">
                <CalendarIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">May 1 - June 30</span>
              </div>
            </div>
            <div className="flex items-center gap-2 mb-4">
              <ShieldIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <p className="text-gray-600 dark:text-gray-400">Algorithms</p>
              <div className="bg-yellow-500 text-white px-2 py-1 rounded-full text-xs font-bold flex items-center gap-1">
                <PuzzleIcon className="w-4 h-4" />
                3
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Explore the fundamentals of algorithms and their applications in various fields.
            </p>
          </div>
        </Link>
        <Link
          className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          href="#"
        >
          <div className="p-6">
            <div className="flex items-center justify-between mb-2">
              <h2 className="text-xl font-bold">The Art of War</h2>
              <div className="flex items-center">
                <UsersIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">22/25</span>
              </div>
            </div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center">
                <div className="flex items-center">
                  <CoinsIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                  <span className="text-gray-600 dark:text-gray-400">Penalty: 10,000 KRW</span>
                </div>
              </div>
              <div className="flex items-center">
                <CalendarIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">April 15 - July 15</span>
              </div>
            </div>
            <div className="flex items-center gap-2 mb-4">
              <BookIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <p className="text-gray-600 dark:text-gray-400">The Art of War</p>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Dive into the timeless wisdom of Sun Tzu's "The Art of War" and explore its application in various
              domains.
            </p>
          </div>
        </Link>
        <Link
          className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          href="#"
        >
          <div className="p-6">
            <div className="flex items-center justify-between mb-2">
              <h2 className="text-xl font-bold">Web Development Masterclass</h2>
              <div className="flex items-center">
                <UsersIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">18/20</span>
              </div>
            </div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center">
                <div className="flex items-center">
                  <CoinsIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                  <span className="text-gray-600 dark:text-gray-400">Penalty: 10,000 KRW</span>
                </div>
              </div>
              <div className="flex items-center">
                <CalendarIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">June 1 - August 31</span>
              </div>
            </div>
            <div className="flex items-center gap-2 mb-4">
              <ShieldIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <p className="text-gray-600 dark:text-gray-400">Web Development</p>
              <div className="bg-blue-500 text-white px-2 py-1 rounded-full text-xs font-bold flex items-center gap-1">
                <PuzzleIcon className="w-4 h-4" />
                4
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Dive deep into the world of web development, covering HTML, CSS, JavaScript, and modern frameworks.
            </p>
          </div>
        </Link>
        <Link
          className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          href="#"
        >
          <div className="p-6">
            <div className="flex items-center justify-between mb-2">
              <h2 className="text-xl font-bold">Data Visualization with Python</h2>
              <div className="flex items-center">
                <UsersIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">12/15</span>
              </div>
            </div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center">
                <div className="flex items-center">
                  <CoinsIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                  <span className="text-gray-600 dark:text-gray-400">Penalty: 10,000 KRW</span>
                </div>
              </div>
              <div className="flex items-center">
                <CalendarIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">July 1 - September 30</span>
              </div>
            </div>
            <div className="flex items-center gap-2 mb-4">
              <ShieldIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <p className="text-gray-600 dark:text-gray-400">Data Visualization</p>
              <div className="bg-green-500 text-white px-2 py-1 rounded-full text-xs font-bold flex items-center gap-1">
                <PuzzleIcon className="w-4 h-4" />
                2
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Explore the world of data visualization using Python libraries like Matplotlib, Seaborn, and Plotly.
            </p>
          </div>
        </Link>
        <Link
          className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          href="#"
        >
          <div className="p-6">
            <div className="flex items-center justify-between mb-2">
              <h2 className="text-xl font-bold">Blockchain Development Fundamentals</h2>
              <div className="flex items-center">
                <UsersIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">10/12</span>
              </div>
            </div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center">
                <div className="flex items-center">
                  <CoinsIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                  <span className="text-gray-600 dark:text-gray-400">Penalty: 10,000 KRW</span>
                </div>
              </div>
              <div className="flex items-center">
                <CalendarIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">May 15 - August 15</span>
              </div>
            </div>
            <div className="flex items-center gap-2 mb-4">
              <ShieldIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <p className="text-gray-600 dark:text-gray-400">Blockchain</p>
              <div className="bg-orange-500 text-white px-2 py-1 rounded-full text-xs font-bold flex items-center gap-1">
                <PuzzleIcon className="w-4 h-4" />
                3
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Dive into the world of blockchain technology and learn how to build decentralized applications.
            </p>
          </div>
        </Link>
        <Link
          className="bg-white rounded-lg shadow-md overflow-hidden dark:bg-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          href="#"
        >
          <div className="p-6">
            <div className="flex items-center justify-between mb-2">
              <h2 className="text-xl font-bold">Ethical Hacking Bootcamp</h2>
              <div className="flex items-center">
                <UsersIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">8/10</span>
              </div>
            </div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center">
                <div className="flex items-center">
                  <CoinsIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                  <span className="text-gray-600 dark:text-gray-400">Penalty: 10,000 KRW</span>
                </div>
              </div>
              <div className="flex items-center">
                <CalendarIcon className="w-5 h-5 text-gray-500 mr-2 dark:text-gray-400" />
                <span className="text-gray-600 dark:text-gray-400">June 15 - September 15</span>
              </div>
            </div>
            <div className="flex items-center gap-2 mb-4">
              <ShieldIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <p className="text-gray-600 dark:text-gray-400">Ethical Hacking</p>
              <div className="bg-red-500 text-white px-2 py-1 rounded-full text-xs font-bold flex items-center gap-1">
                <PuzzleIcon className="w-4 h-4" />
                5
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Learn the fundamentals of ethical hacking and cybersecurity to protect your systems and data.
            </p>
          </div>
        </Link>
      </div>
      <div className="flex justify-center mt-8">
        <Pagination>
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious href="#" />
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#">1</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#" isActive>
                2
              </PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#">3</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationEllipsis />
            </PaginationItem>
            <PaginationItem>
              <PaginationNext href="#" />
            </PaginationItem>
          </PaginationContent>
        </Pagination>
      </div>
    </div>
  )
}

function BookIcon(props: Record<string, string>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function CalendarIcon(props: Record<string, string>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function CoinsIcon(props: Record<string, string>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="8" r="6" />
      <path d="M18.09 10.37A6 6 0 1 1 10.34 18" />
      <path d="M7 6h1v4" />
      <path d="m16.71 13.88.7.71-2.82 2.82" />
    </svg>
  )
}


function PlusIcon(props: Record<string, string>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function PuzzleIcon(props: Record<string, string>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19.439 7.85c-.049.322.059.648.289.878l1.568 1.568c.47.47.706 1.087.706 1.704s-.235 1.233-.706 1.704l-1.611 1.611a.98.98 0 0 1-.837.276c-.47-.07-.802-.48-.968-.925a2.501 2.501 0 1 0-3.214 3.214c.446.166.855.497.925.968a.979.979 0 0 1-.276.837l-1.61 1.61a2.404 2.404 0 0 1-1.705.707 2.402 2.402 0 0 1-1.704-.706l-1.568-1.568a1.026 1.026 0 0 0-.877-.29c-.493.074-.84.504-1.02.968a2.5 2.5 0 1 1-3.237-3.237c.464-.18.894-.527.967-1.02a1.026 1.026 0 0 0-.289-.877l-1.568-1.568A2.402 2.402 0 0 1 1.998 12c0-.617.236-1.234.706-1.704L4.23 8.77c.24-.24.581-.353.917-.303.515.077.877.528 1.073 1.01a2.5 2.5 0 1 0 3.259-3.259c-.482-.196-.933-.558-1.01-1.073-.05-.336.062-.676.303-.917l1.525-1.525A2.402 2.402 0 0 1 12 1.998c.617 0 1.234.236 1.704.706l1.568 1.568c.23.23.556.338.877.29.493-.074.84-.504 1.02-.968a2.5 2.5 0 1 1 3.237 3.237c-.464.18-.894.527-.967 1.02Z" />
    </svg>
  )
}


function ShieldIcon(props: Record<string, string>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
    </svg>
  )
}


function UsersIcon(props: Record<string, string>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
